#!/usr/bin/env python3

import sys
import os
import anyio
import asyncclick as click

from victron.dbus import Dbus
from victron.dbus.monitor import DbusMonitor
from victron.inv import InvControl
from moat.dbus import DbusInterface  # XXX move
from asyncdbus.message_bus import MessageBus, BusType

import logging
logger = logging.getLogger(__name__)

_modes="""
Modes:

\b
"""
for _i,_v in InvControl.MODE.items():
	_n,_p = _v

	_modes += f"{_i :2d} {_n :<10s} {_p.__doc__}\n"

@click.command(epilog=_modes)
@click.option("--debug", "-d", is_flag=True)
@click.option("--mode", "-m", type=int, help="Inverter mode", default=0)
async def main(debug, mode):
	"""
	This program controls a Victron Energy inverter.
	"""
	# Init logging
	logging.basicConfig(level=logging.DEBUG if debug else logging.INFO)
	logger.debug(__file__ + " is starting up")

	import os
	import sys
	sys.path.insert(0, "/data/moat")
	sys.path.insert(1, "/data/moat/bus/python")

	cfg = {'mode': mode}

	async with MessageBus(bus_type=BusType.SYSTEM).connect() as bus, \
                InvControl(bus, cfg) as inv:
            await inv.run()

if __name__ == "__main__":
	main(_anyio_backend="trio")
